// compile with - C++17
//
// g++ -v -Wall -Weffc++ -std=c++17 test_c++.cc -o test_c++
// -v 		    verbose show commands issued by compiler / linker
// -Wall 	    show c++ related warnnings
// -Weff++ 	  warning generated by code that breaks coding advice in Effective C++ - S.Meyers   
// -g  		    include debugger information
// -std=c++17 __cplusplus=201703 => C++ Standard=C++17

// GDB-LLDB command map - https://lldb.llvm.org/use/map.html
// Intro LLDB - https://towardsdatascience.com/an-introduction-to-debugging-in-c-and-lldb-part-i-e3c51991f83a
// LLDB command format - <noun> <verb> [-options [option-value]] [argument [argument...]]
//						  |		  |
//	target (thread, frame etc)	  |
//							   command
//
// (lldb) breakpoint set -l 39					# set BP at line 39
// (lldb) settings show target.run-args			# show args passed in to start
// target.run-args (array of strings) =
//   [0]: "turkey"
//   [1]: "cruffins"
// (lldb) thread step-in 						# step in
// (lldb) step 
// (lldb) s
// (lldb) thread step-over 						# step over
// (lldb) next 
// (lldb) n 
// (lldb) thread step-out 						# step out of current frame
// (lldb) finish 
// (lldb) breakpoint set --name main 			# set BP function main
// (lldb) br s -n main 
// (lldb) b main
// (lldb) breakpoint list 						# list BPs
// (lldb) br l
// (lldb) breakpoint delete 1 					# del BP
// (lldb) br del 1
// 												# set BP in FILE at LINE no.
// (lldb) breakpoint set --file test.c --line 12 		
// (lldb) br s -f test.c -l 12 
// (lldb) b test.c:12
// 												# conditional BP
// (lldb) breakpoint set --name foo --condition '(int)strcmp(y,"hello") == 0' 
// (lldb) br s -n foo -c '(int)strcmp(y,"hello") == 0'
											

// quick note about python2 - err WTF? yep . .
// https://www.legendiary.at/2016/11/27/lldb-nameerror-name-run_one_line-is-not-defined/
// and a fix: https://github.com/Homebrew/homebrew-core/issues/2730
// quick answer its a python dependency issue
// easy fix: $ python3 -m venv venv											# create clean environment
//           $ . venv/bin/activate											# activate it
//           $ g++ -v -Wall -Weffc++ -g null_ref.cc interface_demo.cc -o null_ref	# compile c++
//           $ lldb null_ref turkey cruffins								# fire up debugger w/ args
//           (lldb) run 													# execute
//           Process 29761 launched: '/Users/simon/a_syllabus/lang/c++/
//           compile_hello_world_refs_pointers/null_ref' (x86_64)


//#include<cassert>
//#include<iostream>
//using namespace std;
//
//#include"interface_demo.h"
//
//
//unsigned int read_io_pin_00 (void) {
//	volatile int port_pins = 0x50;		// simulate a port read
//										
//	return port_pins & 0x01;	
//}
//
//// call_stack(5) to create a 5 frame call stack
//// set BP on new_depths = 0xFF0
//int call_stack(int deep, int how_deep = 0){
//	
//	volatile long int new_depths = 0xFF << how_deep;
//	
//	cout << new_depths << endl;
//	
//	if (how_deep <= deep)
//		call_stack(deep, how_deep+1);
//	
//	return 0; 
//}

// std::cout << a << b << '\n';
// std::cout << n << ", " << n << ", " << n << ", " << n << ", " << " \n";
#include <iostream>
//#include <string>
//#include <algorithm>  // std::find, std::for_each

void p(int v, std::string msg=""){
    std::cout << msg << ": " << v << " \n";  
}

//#include <vector>
//void pv(std::vector<int> v, std::string msg=""){
//    std::cout << msg << ": " << "v = { ";
//    for (int n : v) {
//        std::cout << n << " ";
//    }
//    std::cout << "}; \n" << std::endl;  
//}



// https://cppquiz.org/ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// q119.cc

int main() {
  void * p = &p;                            // define void* p initialise it to its own address
  std::cout << bool(p) << std::endl;;       // bool()  cast p to bool 
}

// INPECT POINTER VALUE & ADDRESS W/ DEBUGGER
//
// compile with debugger info
// g++ -g -v -Wall -Weffc++ -std=c++17 test_c++.cc -o test_c++
// start debugger
// list code
// set break point after assignment of p
// run code - hits BP
// inspect frame vars (> fr v)
// inspect expresssion p and &p
//
// (venv)  gdb_lldb % lldb ./test_c++
// (lldb) target create "./test_c++"
// Current executable set to '../gdb_lldb/test_c++' (x86_64).

// (lldb) l
//    110 	int main() {
//    111 	  void * p = &p;
//    112 	  std::cout << bool(p) << std::endl;;
//    113 	}

// (lldb) b test_c++.cc:112
// Breakpoint 1: where = test_c++`main + 23 at test_c++.cc:112:21, address = 0x0000000100003007

// (lldb) r
// Process 5541 launched: '../gdb_lldb/test_c++' (x86_64)
// Process 5541 stopped
// * thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
//     frame #0: 0x0000000100003007 test_c++`main at test_c++.cc:112:21
//    109 	
//    110 	int main() {
//    111 	  void * p = &p;
// -> 112 	  std::cout << bool(p) << std::endl;;
//    113 	}
// Target 0: (test_c++) stopped.

// (lldb) fr v
// (void *) p = 0x00007ffeefbfefb8

// (lldb) expression p
// (void *) $0 = 0x00007ffeefbfefb8

// (lldb) expression &p
// (void **) $1 = 0x00007ffeefbfefb8



// As defined in §[basic.scope.pdecl]¶1, the point of name declaration is after its
// complete declarator and before its initialisation. This
// means that line 4 is valid C++, because it's possible
// to initialise the variable p with the address of an existing
// variable, even if it is its own address.
// 
// The value of p is unknown, but can not be a null pointer value. The
// cast must thus evaluate to 1 and initialise the temporary
// bool as true.


