// compile with - C++17
//
// g++ -v -Wall -Weffc++ -std=c++17 main.cc -o main
//
// produce assembly intermediate file -S
// g++ -v -Wall -Weffc++ -std=c++17 -S main.cc Math.cc Log.cc main
//
// -v 		    verbose show commands issued by compiler / linker
// -Wall 	    show c++ related warnnings
// -Weff++ 	  warning generated by code that breaks coding advice in Effective C++ - S.Meyers
// -g  		    include debugger information
// -std=c++17 __cplusplus=201703 => C++ Standard=C++17

// GDB-LLDB command map - https://lldb.llvm.org/use/map.html
// Intro LLDB - https://towardsdatascience.com/an-introduction-to-debugging-in-c-and-lldb-part-i-e3c51991f83a
// LLDB command format - <noun> <verb> [-options [option-value]] [argument [argument...]]
//						  |		  |
//	target (thread, frame etc)	  |
//							   command
//

#include<iostream>

// data types sizeof
// https://timsong-cpp.github.io/cppwp/n4659/#dcl.dcl

int main() {
    
    // declarations
    // https://timsong-cpp.github.io/cppwp/n4659/dcl.stc

    // https://www.w3schools.com/cpp/cpp_data_types.asp
    // int myNum = 5;               // Integer (whole number)
    // float myFloatNum = 5.99;     // Floating point number
    // double myDoubleNum = 9.98;   // Floating point number
    // char myLetter = 'D';         // Character
    // bool myBoolean = true;       // Boolean
    // string myText = "Hello";     // String
    
                                    // sizeof - bytes
                                    // osx/i7
    bool z = true;                  // 1   
    char a = 'A';                   // 1   
    short b = 32;                   // 2   
    int c = 44;                     // 4   
    long d = 2394;                  // 8   
    long long e = 240802344;        // 8   
                                    // 
    float f = 5.3f;                 // 4   
    float g = 5.9;                  // 4   
    double h = 500.345;             // 8   
    long double l = 2500.9485;      // 16    
    
    

    std::cout << " bool                    " << "   " <<sizeof(z)  << "   " << z <<  '\n';
    std::cout << " char                    " << "   " <<sizeof(a)  << "   " << a <<  '\n';
    std::cout << " short                   " << "   " <<sizeof(b)  << "   " << b <<  '\n';
    std::cout << " int                     " << "   " <<sizeof(c)  << "   " << c <<  '\n';
    std::cout << " long                    " << "   " <<sizeof(d)  << "   " << d <<  '\n';
    std::cout << " long long               " << "   " <<sizeof(e)  << "   " << e <<  '\n';
    std::cout << "                         " <<                                      '\n';
    std::cout << " float 5.3f              " << "   " <<sizeof(f)  << "   " << f <<  '\n';
    std::cout << " float                   " << "   " <<sizeof(g)  << "   " << g <<  '\n';
    std::cout << " double                  " << "   " <<sizeof(h)  << "   " << h <<  '\n';
    std::cout << " long double             " << "   " <<sizeof(l)  << "   " << l <<  '\n';
    
}
// o/p
 //bool                       1   1
 //char                       1   A
 //short                      2   32
 //int                        4   44
 //long                       8   2394
 //long long                  8   240802344
 //                        
 //float 5.3f                 4   5.3
 //float                      4   5.9
 //double                     8   500.345
 //long double                16   2500.95   

