// compile with - C++17
//
// g++ -v -Wall -Weffc++ -std=c++17 main.cc Math.cc Log.cc -o main
//
// produce assembly intermediate file -S
// g++ -v -Wall -Weffc++ -std=c++17 -S main.cc Math.cc Log.cc main
//
// -v 		    verbose show commands issued by compiler / linker
// -Wall 	    show c++ related warnnings
// -Weff++ 	  warning generated by code that breaks coding advice in Effective C++ - S.Meyers
// -g  		    include debugger information
// -std=c++17 __cplusplus=201703 => C++ Standard=C++17

// GDB-LLDB command map - https://lldb.llvm.org/use/map.html
// Intro LLDB - https://towardsdatascience.com/an-introduction-to-debugging-in-c-and-lldb-part-i-e3c51991f83a
// LLDB command format - <noun> <verb> [-options [option-value]] [argument [argument...]]
//						  |		  |
//	target (thread, frame etc)	  |
//							   command
//

//#include<iostream>
#include"Log.h"
#include"Math.h"

int main() {

    char const *b = "Log message";    
    Log(b);
    
    Add(2,6);
    Mul(4,15);
}


